config={api:"http://162.243.86.247/",authUrl:"http://162.243.86.247/auth.php",dataGroups:["schools","buildings","building-elements"],surveyStartDate:"2015-10-23"};sessionGlobals={};
function UI_DataHList(e,f,b){function g(a){a.forEach(function(a,f){var h=$('<span class="datapoint"></span>').append($("<a class='pdf-export'>PDF</a>").attr({href:b+"download.php?emis="+a.emis+"&key="+sessionGlobals.key+(sessionGlobals.surveyor_id?"&surveyor_id="+sessionGlobals.surveyor_id:""),target:"_blank"})).append($("<a class='webpage-view'>HTML</a>").attr({href:b+"view.php?emis="+a.emis+"&key="+sessionGlobals.key+(sessionGlobals.surveyor_id?"&surveyor_id="+sessionGlobals.surveyor_id:""),target:"_blank"}));
h.append($("<span></span>").attr({"class":"emis"}).text(a.emis));h.append($("<span></span>").attr({"class":"date"}).text(a["submission-date"]));h.append($("<span></span>").attr({"class":"surveyor-id"}).text(a["surveyor-id"]));$("<span class='ui-trigger-container'/>").appendTo(h);$("<div class='ui-hlist-container'/>").appendTo(h).click(function(a){a.stopPropagation()});d.append(h)})}var d=$("<div/>").addClass("data-view-list");this.update=function(a){d.empty();g(a)};g(e);$.extend(!0,this,d)}
function UI_DateRangeAndString(e){var f=this,b=$("<div/>").addClass("ui-date-range-and-string-search"),g=$("<input class='ui-searchbox' type='text' placeholder='Enter EMIS or Surveyor ID to filter the list below'/>").appendTo(b),d=$("<input class='ui-start-date' type='date'/>").appendTo(b),a=$("<input class='ui-end-date' type='date'/>").appendTo(b);d[0].value=e["default-start-date"];a[0].value=e["default-end-date"];$.extend(!0,this,b);$(b).find("input[type='date']").change(function(a){e["event-handlers"]["on-query"].call(f,
a)});$(b).find("input[type='text']").keyup(function(a){e["event-handlers"]["on-query"].call(f,a)});this.getQueryObject=function(){return{string:g[0].value,"start-date":(new Date(d[0].value)).toJSON().split("T")[0],"end-date":(new Date(a[0].value)).toJSON().split("T")[0]}}}
function UI_LoginPrompt(e){function f(){$.ajax({url:e.authUrl,data:{auth1:g.val(),auth2:CryptoJS.AES.encrypt(d.val(),d.val()).toString()},success:function(a){JSON.parse(a).authorized?e.eventHandlers.authorized(JSON.parse(a).session):alert("Invalid Credentials!")},method:"POST"})}var b=$("<div class='alert-box'></div>"),g=$("<input type='text' class='username' placeholder='username'/>").appendTo(b),d=$("<input type='password' class='password' placeholder='password'/>").appendTo(b);d.keyup(function(a){13===
a.keyCode&&f()});$("<a class='ui-button'>Login</a>").click(function(){f()}).appendTo(b);return $.extend(this,b)}
function jsonArraySearch(e,f,b){var g=[];e.forEach(function(d,a){var k=Object.keys(d);for(c in k){var e=d[k[c]];if(b["key-value-in-range"]){if(d[b["key-value-in-range"].key]>=b["key-value-in-range"]["range-start"]&&d[b["key-value-in-range"].key]<=b["key-value-in-range"]["range-end"]&&e.toString().match(new RegExp(f,"gi"))){g.push(d);break}}else if(e.toString().match(new RegExp(f,"gi"))){g.push(d);break}}});return g}
$(document).ready(function(){function e(){$.ajax({url:config.api+"download.php?key="+sessionGlobals.key+(sessionGlobals.surveyor_id?"&surveyor_id="+sessionGlobals.surveyor_id:""),success:function(a){a=a.split("|");a[0]=a[0].split(";");a[1]=a[1].split(";");a[2]=a[2].split(";");a[0].forEach(function(b,d){f.push({emis:"EMIS"+b,"submission-date":a[1][d],"surveyor-id":a[2][d]})});b=new UI_DataHList(jsonArraySearch(f,"",{"key-value-in-range":{key:"submission-date","range-start":(new Date(new Date-864E6)).toJSON().split("T")[0],
"range-end":(new Date).toJSON().split("T")[0]}}),config.dataGroups,config.api);$("#app").append(b)}});uiQueryField=new UI_DateRangeAndString({"default-start-date":(new Date(new Date-864E6)).toJSON().split("T")[0],"default-end-date":(new Date).toJSON().split("T")[0],"event-handlers":{"on-query":function(a){864E6<new Date(this.getQueryObject()["end-date"])-new Date(this.getQueryObject()["start-date"])?($(".ui-large-button.with-pictures").addClass("passive"),$(".ui-large-button.with-pictures").parent().addClass("passive")):
($(".ui-large-button.with-pictures").removeClass("passive"),$(".ui-large-button.with-pictures").parent().removeClass("passive"));b.update(jsonArraySearch(f,this.getQueryObject().string,{"key-value-in-range":{key:"submission-date","range-start":this.getQueryObject()["start-date"],"range-end":this.getQueryObject()["end-date"]}}))}}});uiQueryField.appendTo("#app");var d=$("<div class='update-msg'></div>").appendTo("#app");$.ajax({url:config.api+"download.php?query=gettimestamp&key="+sessionGlobals.key+
(sessionGlobals.surveyor_id?"&surveyor_id="+sessionGlobals.surveyor_id:""),success:function(a){a=Number(a);updatetime="Last update: "+Math.floor(a/3600)+"h"+Math.floor(60*(a/3600-Math.floor(a/3600)))+"m ago.";d.text(updatetime);setInterval(function(){updatetime="Last update: "+Math.floor(a/3600)+"h"+Math.floor(60*(a/3600-Math.floor(a/3600)))+"m ago.";d.text(updatetime);a+=60},6E4)}});navigator.userAgent.match(/chrome/i)||(uiQueryField.find(".ui-start-date").datepicker({format:"yy-mm-dd"}).datepicker("setDate",
new Date(config.surveyStartDate)),uiQueryField.find(".ui-end-date").datepicker({format:"yy-mm-dd"}).datepicker("setDate",new Date));$("<div class='ui-raw-download-list'/>").append(function(){return $("<a class='ui-large-button with-pictures'>Download Data (Including Photographs)</a>").click(function(a){var b=this;$.ajax({url:config.api+"script.php?tablename=school&startdate="+uiQueryField.getQueryObject()["start-date"]+"&enddate="+uiQueryField.getQueryObject()["end-date"]+"&string="+uiQueryField.getQueryObject().string+
"&key="+sessionGlobals.key+(sessionGlobals.surveyor_id?"&surveyor_id="+sessionGlobals.surveyor_id:""),success:function(a){$(b).parent().find("a.ui-hlist").remove();""===a?$(b).parent().append($("<a class='ui-hlist-item error'/>").text("Date range too large. Please try a smaller range of dates.")):$(b).parent().append($("<a class='ui-hlist-item' target='_blank'/>").attr({href:config.api+"downloads/"+sessionGlobals.key.split("-")[1]+"/"+a}).text(a));$.ajax({url:config.api+"script.php?tablename=building&startdate="+
uiQueryField.getQueryObject()["start-date"]+"&enddate="+uiQueryField.getQueryObject()["end-date"]+"&string="+uiQueryField.getQueryObject().string+"&key="+sessionGlobals.key+(sessionGlobals.surveyor_id?"&surveyor_id="+sessionGlobals.surveyor_id:""),success:function(a){""===a?$(b).parent().append($("<a class='ui-hlist-item error'/>").text("Date range too large. Please try a smaller range of dates.")):$(b).parent().append($("<a class='ui-hlist-item' target='_blank'/>").attr({href:config.api+"downloads/"+
sessionGlobals.key.split("-")[1]+"/"+a}).text(a));$.ajax({url:config.api+"script.php?tablename=buildingelement&startdate="+uiQueryField.getQueryObject()["start-date"]+"&enddate="+uiQueryField.getQueryObject()["end-date"]+"&string="+uiQueryField.getQueryObject().string+"&key="+sessionGlobals.key+(sessionGlobals.surveyor_id?"&surveyor_id="+sessionGlobals.surveyor_id:""),success:function(a){""===a?$(b).parent().append($("<a class='ui-hlist-item error'/>").text("Date range too large. Please try a smaller range of dates.")):
$(b).parent().append($("<a class='ui-hlist-item' target='_blank'/>").attr({href:config.api+"downloads/"+sessionGlobals.key.split("-")[1]+"/"+a}).text(a))}})}})}})})}).appendTo("#app");$("<div class='ui-raw-download-list'/>").append(function(){return $("<a class='ui-large-button'>Download CSV Only</a>").click(function(a){var b=this;$.ajax({url:config.api+"script.php?tablename=school&startdate="+uiQueryField.getQueryObject()["start-date"]+"&enddate="+uiQueryField.getQueryObject()["end-date"]+"&query=csvonly&key="+
sessionGlobals.key+(sessionGlobals.surveyor_id?"&surveyor_id="+sessionGlobals.surveyor_id:""),success:function(a){$(b).parent().find("a.ui-hlist").remove();""===a?$(b).parent().append($("<a class='ui-hlist-item error'/>").text("Date range too large. Please try a smaller range of dates.")):$(b).parent().append($("<a class='ui-hlist-item' target='_blank'/>").attr({href:config.api+a.replace(".zip",".csv")+"?key="+sessionGlobals.key}).text(a.replace(".zip",".csv")));$.ajax({url:config.api+"script.php?tablename=building&startdate="+
uiQueryField.getQueryObject()["start-date"]+"&enddate="+uiQueryField.getQueryObject()["end-date"]+"&query=csvonly&key="+sessionGlobals.key+(sessionGlobals.surveyor_id?"&surveyor_id="+sessionGlobals.surveyor_id:""),success:function(a){""===a?$(b).parent().append($("<a class='ui-hlist-item error'/>").text("Date range too large. Please try a smaller range of dates.")):$(b).parent().append($("<a class='ui-hlist-item' target='_blank'/>").attr({href:config.api+a.replace(".zip",".csv")+"?key="+sessionGlobals.key}).text(a.replace(".zip",
".csv")));$.ajax({url:config.api+"script.php?tablename=buildingelement&startdate="+uiQueryField.getQueryObject()["start-date"]+"&enddate="+uiQueryField.getQueryObject()["end-date"]+"&query=csvonly&key="+sessionGlobals.key+(sessionGlobals.surveyor_id?"&surveyor_id="+sessionGlobals.surveyor_id:""),success:function(a){""===a?$(b).parent().append($("<a class='ui-hlist-item error'/>").text("Date range too large. Please try a smaller range of dates.")):$(b).parent().append($("<a class='ui-hlist-item' target='_blank'/>").attr({href:config.api+
a.replace(".zip",".csv")+"?key="+sessionGlobals.key}).text(a.replace(".zip",".csv")))}})}})}})})}).appendTo("#app")}var f=[],b,g=$("<div id='login-prompt'><h4 class='msg'>Please login to continue..</h4></div>").appendTo("body");(new UI_LoginPrompt({authUrl:config.authUrl,eventHandlers:{authorized:function(b){sessionGlobals={surveyor_id:b.surveyor_id,key:b.key};g.remove();e()}}})).appendTo(g);$("#export-tab").click(function(){$(".data-view-list").remove()});$("#view-tab").click(function(){$(".data-export-tool").remove();
$("#app").append($(new UI_DataHList(f,config.dataGroups,config.api)))})});
